name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Required for creating releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up build environment
        uses: actions/setup-java@v4  # or setup-node@v4, setup-go@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test
        run: |
          mvn clean package
          mvn test

      - name: Generate release notes
        id: release_notes
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 $TAG_NAME^ 2>/dev/null || echo "")
          
          if [ -n "$PREVIOUS_TAG" ]; then
            git log --pretty=format:"- %s" $PREVIOUS_TAG..$TAG_NAME > release_notes.txt
          else
            echo "- Initial release" > release_notes.txt
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release_notes.txt
          files: |
            target/*.jar
            dist/*.zip
            *.tar.gz
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}