name: Release to Maven Central

on:
  push:
    tags:
      - 'v*'
  # Allow manual workflow runs
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: ossrh
          server-username: ${{ secrets.SONATYPE_USERNAME }}
          server-password: ${{ secrets.SONATYPE_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          cache: 'maven'

      - name: Test Sonatype login via API
        run: |
          curl -u "${{ secrets.SONATYPE_USERNAME }}:${{ secrets.SONATYPE_PASSWORD }}" \
          -X GET "https://oss.sonatype.org/service/local/status"

      - name: Check settings.xml
        run: |
          # Will remove the sensitive information from the output
          cat ~/.m2/settings.xml
          echo
          echo "Validating settings.xml configuration..."
          # Check if settings.xml is correctly configured (without exposing contents)
          if ! grep -q "<id>ossrh</id>" ~/.m2/settings.xml; then
            echo "settings.xml is not configured correctly for Sonatype OSSRH."
            exit 1
          fi
          # Check if GPG configuration exists (using extended regex for any passphrase content)
          if ! grep -E "<passphrase>.+</passphrase>" ~/.m2/settings.xml; then
            echo "settings.xml is not configured correctly for gpg-passphrase."
            exit 1
          fi
          echo "settings.xml configuration validated successfully"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Change Version
        run: |
          mvn versions:set -DnewVersion=${GITHUB_REF#refs/tags/} -DgenerateBackupPoms=false
          echo "Version set to ${GITHUB_REF#refs/tags/}"

      - name: Build and Test
        run: mvn clean verify -Pci

      - name: Deploy to Maven Central
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          mvn clean deploy -P deploy,release -DskipTests

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}